sudo: false
language: php

php:
  - 7.1
  - 7.2

before_script:
  - phpenv rehash
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
  - ./vendor/bin/phpunit -v
